project_id = "qrxsiixufdiemwwyhxvd"

[functions.save-campaign]
verify_jwt = false

[functions.enqueue-campaign]
verify_jwt = false

[functions.process-whatsapp-queue]
verify_jwt = false

[functions.wa-inbox-webhook]
verify_jwt = false

[functions.wa-send-reply]
verify_jwt = false

[functions.extract-google-maps-leads]
verify_jwt = false

[functions.wa-extract-groups]
verify_jwt = false

[functions.sanitize-contacts]
verify_jwt = false