ALTER TABLE meta_capi_batches
  ADD COLUMN IF NOT EXISTS events_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS meta_response JSONB,
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ DEFAULT now(),
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;